#!/bin/bash
echo "🚀 Setting up Python dependencies..."
echo "📦 Updating Poetry dependencies..."
poetry update
echo "🔧 Installing dependencies..."
poetry install
echo "✅ Setup complete!"
echo ""
echo "🎯 Available development tools:"
echo ""
echo "  📝 CODE QUALITY:"
echo "    • poetry run python -m ruff check .      # Fast linting & error detection"
echo "    • poetry run python -m ruff format .     # Code formatting (like black)"
echo "    • poetry run python -m pylint app/       # Deep code analysis & complexity"
echo ""
echo "  🔍 TYPE CHECKING:"
echo "    • poetry run python -m mypy .            # Static type checking"
echo ""
echo "  🧪 TESTING:"
echo "    • poetry run python -m pytest            # Run all tests"
echo "    • poetry run python -m pytest -v        # Verbose test output"
echo "    • poetry run python -m pytest -k test_name  # Run specific test"
echo ""
echo "  📁 FILE WATCHING:"
echo "    • poetry run python -m watchdog          # File change monitoring"
echo ""
echo "  🚀 YOUR CODE:"
echo "    • poetry run python /app/main.py        # Run your NiceGUI app"
echo "    • poetry run python /workspaces/app.py  # Run your app from workspace"
echo ""
echo "💡 Tips:"
echo "  • Use 'poetry run python -m' for development tools"
echo "  • Use 'poetry run python' directly for your own scripts"
echo "  • Ruff is fast for daily use, Pylint for deep analysis"
echo "  • Run 'poetry run python -m ruff check . --fix' to auto-fix issues"
echo ""
echo "🎉 Happy coding!"